apiVersion: vm.proxmox.jet.crossplane.io/v1alpha1
kind: Qemu
metadata:
  name: test-vm
spec:
  forProvider:
    agent: 1
    automaticReboot: true
    bios: seabios
    boot: c
    bootdisk: scsi0
    cicustom: user=local:snippets/cloud-init-user.conf,network=local:snippets/cloud-init-network.conf
    clone: base-rockylinux-x86
    cores: 8
    disk:
    - size: 40G
      slot: 0
      storage: local-lvm
      type: scsi
    fullClone: true
    hotplug: network,disk,usb
    kvm: true
    memory: 16384
    network:
    - bridge: vmbr0
      macaddr: 58:b9:53:85:32:a7
      model: virtio
    onboot: true
    vm_state: running
    osType: cloud-init
    qemuOs: other
    scsihw: virtio-scsi-pci
    sockets: 1
    tablet: true
    targetNode: pm1
    vmid: 100
  providerConfigRef:
    name: default
